num_workers: &num_workers 4

NAIVE_STAGE:
  latest:
    loader:
      module: iteration
      args:
        batch_size: 1
        iterations: 100
        num_workers: *num_workers
    dataset_state:
      scale: 8
    model_state: 
      enable_sh: True
  # init:
  #   loader:
  #     module: iteration
  #     args:
  #       batch_size: 1
  #       iterations: 100
  #       num_workers: *num_workers
  #   dataset_state:
  #     scale: 8
  #   model_state: {}
  # tree:
  #   loader:
  #     module: iteration
  #     args:
  #       batch_size: 1
  #       iterations: 200
  #       num_workers: *num_workers
  #   dataset_state:
  #     scale: 4
  #   render_state:
  #     render_depth: False
  #   model_state:
  #     enable_sh: True